apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-helloworld-2
  name: go-helloworld-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-helloworld-2
  template:
    metadata:
      labels:
        app: go-helloworld-2
    spec:
      containers:
      - image: ghcr.io/2022-4400-exp/4498-go-helloworld-2:d8efa90c1940b7fbb834d59ad8de570cf0a36813
        name: go-helloworld-small
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-helloworld-2
  name: go-helloworld-2
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: go-helloworld-2
  type: NodePort
