apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-helloworld-2
  name: go-helloworld-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-helloworld-2
  template:
    metadata:
      labels:
        app: go-helloworld-2
    spec:
      containers:
        - image: ghcr.io/2022-4400-exp/4499-go-helloworld-2:080cc1626b2432fbb18e2b6617e10fab982a0646
          name: go-helloworld-small
