name: "Build"
on: [push]

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: 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

      - name: Build Docker image
        run: |
          docker build . -t ghcr.io/2022-4400-exp/4499-go-helloworld-2:${{ github.sha }}
          docker push ghcr.io/2022-4400-exp/4499-go-helloworld-2:${{ github.sha }}
