name: "Build"
on:
  push:
    paths-ignore:
      - "manifest/**"

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: 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


      - name: Setup buildx
        run: |
          docker buildx create --use --name multi-arch

      - name: Build Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 . -t ghcr.io/2022-4400-exp/4499-go-helloworld-2:${{ github.sha }} --push


      - name: Update manifest image tag
        run: |
          yq eval 'spec.template.spec.containers[0].image = "ghcr.io/2022-4400-exp/4498-go-helloworld-2:"+env(GITHUB_SHA)' -i ./manifest/deployment.yaml
          git diff --name-only --exit-code


      - name: Commit/Push manifest
        if: steps.update-image-tag.outcome == 'failure'
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add .
          git commit --author=. -m "Update image tag to $GITHUB_SHA"
          git push

